[project]
name = "yolo-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "roboflow>=1.2.7",
    "ultralytics>=8.3.191",
]
